<?php

return array(
'AccessDenied' => 'Akses ditolak',
'EditOperationNotPermitted' => 'Tidak diizinkan mengedit data',
'ViewOperationNotPermitted' => 'Tidak diizinkan melihat data',
'DeleteOperationNotPermitted' => 'Tidak diizinkan menghapus data',
'InsertOperationNotPermitted' => 'Tidak diizinkan menambahkan data',
'OperationNotPermitted' => 'Operasi tidak diizinkan',
'AccessDeniedErrorSuggestions' => '<p>Anda tidak memiliki izin untuk mengakses halaman ini. Bisa disebabkan oleh salah satu dari beberapa alasan:</p><ol> <li>Anda belum masuk. Silahkan masuk ke <a class="alert-link" href="%s">Halaman login</a> dan coba kembali.</li> <li>atau anda mungkin tidak memiliki hak akses untuk menjalankan operasi ini.</li> </ol>',
'ClientValidationsErrors' => 'Kesalahan:',
'SaveNewRecord' => 'Simpan',
'BackToList' => 'Kembali ke daftar',
'InsertRecord' => 'Tambah data',
'RequiredField' => 'Kolom harus diisi',
'Save' => 'Simpan',
'SetNull' => 'Atur kosong (NULL)',
'SetDefault' => 'Atur sebagai standar',
'AdvancedSearch' => 'Pencarian lanjutan',
'SearchFor' => 'Mencari data untuk',
'AllConditions' => 'Semua kondisi',
'AnyCondition' => 'Kondisi apapun',
'ApplyAdvancedFilter' => 'Terapkan',
'ResetAdvancedFilter' => 'Atur ulang',
'PageList' => 'Daftar halaman',
'ApplySimpleFilter' => 'Terapkan',
'ResetSimpleFilter' => 'Atur ulang',
'MasterRecord' => 'Data utama',
'ReturnFromDetailToMaster' => 'kembali ke daftar',
'AddNewRecord' => 'Tambah baru',
'PageNumbetOfCount' => 'Halaman {$current_page} dari {$page_count}',
'Delete' => 'Hapus',
'ExportToExcel' => 'Ekspor ke Excel',
'ExportToWord' => 'Ekspor ke Word',
'ExportToXml' => 'Ekspor ke Xml',
'ExportToCsv' => 'Ekspor ke Csv',
'ExportToPdf' => 'Ekspor ke Pdf',
'PrintCurrentPage' => 'Cetak halaman ini',
'PrintAllPages' => 'Cetak semua halaman',
'CurrentPage' => 'Halaman ini',
'PrinterFriendly' => 'Halaman untuk dicetak',
'PageSettings' => 'Pengaturan halaman',
'Appearance' => 'Tampilan',
'ViewMode' => 'Mode lihat',
'CardViewMode' => 'Kartu',
'TableViewMode' => 'Grid',
'CardRowCount' => 'Jumlah kartu dalam satu baris',
'CardRowCountDescription' => 'Di sini Anda dapat memilih jumlah kartu yang akan ditempatkan berturut-turut untuk setiap resolusi layar yang didukung. Resolusi Anda saat ini disorot <strong class="text-success">dalam tanda ini</strong>.',
'View' => 'Lihat',
'Edit' => 'Ubah',
'Copy' => 'Duplikasi',
'KeepImage' => 'Simpan',
'RemoveImage' => 'Hapus',
'ReplaceImage' => 'Ganti',
'FieldValueRequiredErrorMsg' => '%s harus diisi',
'LoggedInAs' => 'Masuk sebagai',
'YouAreNotLoggedIn' => 'Anda belum masuk',
'NoDataToDisplay' => 'Tidak ada data untuk ditampilkan',
'Refresh' => 'Segarkan',
'BinaryDataCanNotBeExportedToXls' => 'Data biner tidak dapat diekspor',
'DetailPreview' => 'Pratinjau detail',
'ShownFirstMofNRecords' => 'Menampilakan %s pertama dari %s data', /* masih rancu */
'FullView' => 'Tampilan penuh',
'RecordsMtoKFromN' => 'Dara %s ke %s dari %s',
'Login' => 'Masuk',
'Guest' => 'Tamu',
'LoginAsGuest' => 'Masuk sebagai tamu',
'Username' => 'User ID',
'Password' => 'Katasandi',
'ConfirmPassword' => 'Konfirmasi katasandi',
'ConfirmedPasswordError' => 'Katasandi tidak sama, silahkan ulangi kembali',
'RememberMe' => 'Ingat saya',
'LoginTitle' => 'Masuk',
'Print' => 'Cetak',
'Export' => 'Ekspor',
'more' => 'lainya',
'CloseWindow' => 'Tutup jendela',
'Back' => 'Kembali',
'Error' => 'Eror',
'ShowErrorDetails' => 'Tampilkan detail',
'CriticalErrorSuggestions' => 'Terjadi kesalahan yang tidak diharapkan. Mungkin karena salah satu dari beberapa alasan:<ul>
<li>Anda mencoba memasukkan data yang salah atau melakukan operasi ilegal;</li>
<li>koneksi ke server telah hilang.</li>
</ul>',
'Not' => 'Tidak',
'ShowHideNavbar' => 'Tampilkan/Sembunyikan Navbar',
'First' => 'Pertama',
'Last' => 'Terakhir',

'equals' => 'sama dengan',
'doesNotEquals' => 'tidak sama dengan',
'isLessThan' => 'kurang dari',
'isLessThanOrEqualsTo' => 'kurang dari atau sama dengan',
'isGreaterThan' => 'lebih besar dari',
'isGreaterThanOrEqualsTo' => 'lebih besar atau sama dengan',
'Like' => 'seperti',
'AnyField' => 'Kolom apapun',
'between' => 'diantara',
'isBlank' => 'datanya kosong',
'isNotBlank' => 'datanya tidak kosong',
'All' => 'Semua',

'Logout' => 'Keluar aplikasi',
'StartsWith' => 'dimulai dengan',
'EndsWith' => 'diakhiri dengan',
'Contains' => 'mengandung',
'SearchCondtitions' => 'kondisi pencarian',
'GuestAccessDenied' => 'Akses untuk tamu tidak diizinkan',
'UsernamePasswordWasInvalid' => 'Kombinasi User ID dan Katasandi yang dimasukan tidak sesuai.',

'ErrorsDuringUpdateProcess' => 'Terjadi kesalahan saat memperbaharui data:',
'ErrorsDuringInsertProcess' => 'Terjadi kesalahan dalam menambahkan data:',
'ErrorsDuringDeleteProcess' => 'Terjadi kesalahan dalam menghapus data:',
'ErrorsDuringDataRetrieving' => 'Gagal menerima data:',

'FileSizeExceedMaxSizeForField' => 'Maksimal ukuran file adalah %s (ukuran Data: %s, maksimal ukuran data: %s) ',
'ImageSizeExceedMaxSizeForField' => 'Maksimal ukuran gambar adalah %s (ukuran gambar: %dx%d, maksimal ukuran gambar: %dx%d) ',

'Actions' => 'Aksi',
'PleaseSelect' => 'Silahkan Pilih...',
'PrintOneRecord' => 'Cetak',

'ChangePageSizeText' => 'Total data: {$row_count}.',
'ChangePageSizeTitle' => 'Ukuran Halaman',
'CustomizePageSize' => '{$rec_count_per_page} data perhalaman',
'RecordsPerPage' => 'Data perhalaman',
'CurrentPageCount' => '{$current_page_count} halaman.',
'CustomRecordsPerPage' => 'Kustom',
'CountRowsWithCountPages' => '{$record_count} ({$page_count} halaman)',
'TotalPages' => 'Total halaman',
'UseCustomPageSize' => 'Gunakan data kustom',
'ViewMode' => 'Mode tampilan',

'EmptyFilter_MessageTitle' => 'Filter kosong',
'EmptyFilter_Message' => 'Harap mengisi setidaknya satu bidang pencarian.',
'Cancel' => 'Batal',
'Ok' => 'Oke',
'Commit' => 'Proses',

'RequiredValidationMessage' => '%s harus diisi.',
'EmailValidationMessage' => 'Silahkan masukan email yang valid.',
'UrlValidationMessage' => 'Silahkan masukan URL yang valid.',
'NumberValidationMessage' => 'Silahkan masukan angka yang valid.',
'DigitsValidationMessage' => 'Masukan hanya digit angka saja.',
'CreditcardValidationMessage' => 'Silahkann masukan kartu kredit yang valid.',
'MaxlengthValidationMessage' => 'Maksimal karakter yang bisa diinput adalah {0} karakter.',
'MinlengthValidationMessage' => 'Silahkan Masukan data minimal {0} karakter.',
'RangelengthValidationMessage' => 'Silahkan masukan data antara {0} sampai {1} karakter.',
'RangeValidationMessage' => 'Silahkan masukan data antara {0} sampai {1}.',
'MaxValidationMessage' => 'Harap masukkan nilai kurang dari atau sama dengan {0}.',
'MinValidationMessage' => 'Masukkan nilai yang lebih besar atau sama dengan {0}.',
'RegExpValidationMessage' => 'Nilai tidak sesuai dengan ekspresi reguler.',

'SaveAndBackToList' => 'Simpan dan kembalikan ke daftar',
'SaveAndInsert' => 'Simpan dan tambahkan data lain',
'SaveAndEdit' => 'Simpan dan lanjutkan pengeditan',

'NotLike' => 'Tidak Seperti',
'NotContains' => 'Tidak mengandung',
'isNotBlank' => 'Tidak Kosong',
'None' => 'Tidak ada',
'CreateFilterConditionFirst' => 'Untuk menampilkan data, <a href="#" class="js-filter-builder-open">buka Filter Builder</a> dan tentukan satu atau beberapa ketentuan. Anda juga dapat menggunakan alat Pencarian Cepat atau Filter Kolom.',
'CreateFilter' => 'Buat filter',
'EditFilter' => 'Ubah filter',
'ResetFilter' => 'Ulangi filter',

'Equals' => 'Sama dengan',
'DoesNotEquals' => 'Tidak sama dengan',
'IsLessThan' => 'Kurang dari',
'IsLessThanOrEqualsTo' => 'Kurang dari atau sama dengan',
'IsGreaterThan' => 'Lebih besar dari',
'IsGreaterThanOrEqualsTo' => 'Lebih besar atau sama dengan',
'Like' => 'Seperti',
'IsBlank' => 'Kosong',
'IsNotBlank' => 'Tidak boleh kosong',
'IsLike' => 'Seperti',
'IsNotLike' => 'Tidak seperti',
'Contains' => 'Mengandung',
'DoesNotContain' => 'Tidak mengandung',
'BeginsWith' => 'Dimulai dengan',
'EndsWith' => 'Diakhir oleh',

'OperatorAnd' => 'Semua',
'OperatorOr' => 'Apapun',
'OperatorNone' => 'Tidak ada',
'OperatorStringAnd' => 'Dan',
'OperatorStringOr' => 'Atau',
'OperatorStringNone' => 'Tidak',

'Loading' => 'Memuat',
'FilterBuilder' => 'Pembuat filter',
'FilterBuilderGroupConditionBeforeRules' => 'Pilih data dimana',
'FilterBuilderGroupConditionAfterRules' => 'dari yang berikut ini',
'DeleteSelectedRecordsQuestion' => 'Hapus data yang dipilih?',

'AddGroup' => 'Tambahkan grup',
'AddCondition' => 'Tambahkan kondisi',
'RemoveGroup' => 'Hapus grup',
'RemoveCondition' => 'Hapus kondisi',
'EnableFilter' => 'Aktifkan filter',
'DisableFilter' => 'Matikan filter',
'DefaultPageSize' => 'Tentukan ukuran halaman',
'SaveChanges' => 'Simpan perubahan',
'SaveAndOpenDetail' => 'Simpan dan buka detail dari "%s"',
'QuickSearch' => 'Pencarian cepat',
'QuickSearchApply' => 'Cari',
'QuickSearchClear' => 'Bersihkan',
'DeleteRecordQuestion' => 'Hapus data?',

'ResetFilterRow' => 'Setel ulang baris filter',
'ManageDetails' => 'Kelola detail',
'ErrorDetails' => 'Rincian kesalahan',
'SetToNull' => 'diatur ke null (kosong)',
'SetToDefault' => 'setel ke default',

'FilterOperatorEquals' => 'Sama dengan',
'FilterOperatorEqualsShort' => '=',
'FilterOperatorDoesNotEqual' => 'Tidak sama dengan',
'FilterOperatorDoesNotEqualShort' => '<>',
'FilterOperatorIsGreaterThan' => 'Lebih besar dari',
'FilterOperatorIsGreaterThanShort' => '>',
'FilterOperatorIsGreaterThanOrEqualTo' => 'Lebih besar atau sama dengan',
'FilterOperatorIsGreaterThanOrEqualToShort' => '>=',
'FilterOperatorIsLessThan' => 'Lebih kecil dari',
'FilterOperatorIsLessThanShort' => '<',
'FilterOperatorIsLessThanOrEqualTo' => 'Lebih kecil atau sama dengan',
'FilterOperatorIsLessThanOrEqualToShort' => '<=',
'FilterOperatorIsBetween' => 'diantara',
'FilterOperatorIsBetweenShort' => 'diantara',
'FilterOperatorIsNotBetween' => 'tidak diantara',
'FilterOperatorIsNotBetweenShort' => 'tidak diantara',
'FilterOperatorContains' => 'Mengandung',
'FilterOperatorContainsShort' => 'Mengandung',
'FilterOperatorDoesNotContain' => 'Tidak mengandung',
'FilterOperatorDoesNotContainShort' => 'Tidak mengandung',
'FilterOperatorBeginsWith' => 'Dimulai dengan',
'FilterOperatorBeginsWithShort' => 'Dimulai dengan',
'FilterOperatorEndsWith' => 'Diakhiri dengan',
'FilterOperatorEndsWithShort' => 'Diakhiri dengan',
'FilterOperatorIsLike' => 'Seperti',
'FilterOperatorIsLikeShort' => 'Seperti',
'FilterOperatorIsNotLike' => 'Tidak seperti',
'FilterOperatorIsNotLikeShort' => 'Tidak seperti',
'FilterOperatorIsBlank' => 'Kosong',
'FilterOperatorIsBlankShort' => 'Kosong',
'FilterOperatorIsNotBlank' => 'tidak kosong',
'FilterOperatorIsNotBlankShort' => 'tidak kosong',
'FilterOperatorDateEquals' => 'Tanggal sama dengan',
'FilterOperatorDateEqualsShort' => 'Tanggal =',
'FilterOperatorDateDoesNotEqual' => 'Tanggal tidak sama dengan',
'FilterOperatorDateDoesNotEqualShort' => 'Date <>',
'FilterOperatorYearEquals' => 'Tahun sama dengan',
'FilterOperatorYearEqualsShort' => 'Tahun =',
'FilterOperatorYearDoesNotEqual' => 'Tahun tidak sama dengan',
'FilterOperatorYearDoesNotEqualShort' => 'Tahun <>',
'FilterOperatorMonthEquals' => 'Bulan sama dengan',
'FilterOperatorMonthEqualsShort' => 'Bulan =',
'FilterOperatorMonthDoesNotEqual' => 'Bulan tidak sama dengan',
'FilterOperatorMonthDoesNotEqualShort' => 'Bulan <>',
'FilterOperatorIn' => 'Didalam',
'FilterOperatorInShort' => 'Didalam',
'FilterOperatorNotIn' => 'Tidak didalam',
'FilterOperatorNotInShort' => 'Tidak didalam',
'FilterOperatorToday' => 'Hari ini',
'FilterOperatorTodayShort' => 'Hari ini',
'FilterOperatorThisMonth' => 'Bulan ini',
'FilterOperatorThisMonthShort' => 'Bulan ini',
'FilterOperatorPrevMonth' => 'Bulan lalu',
'FilterOperatorPrevMonthShort' => 'Bulan lalu',
'FilterOperatorThisYear' => 'Tahun ini',
'FilterOperatorThisYearShort' => 'Tahun ini',
'FilterOperatorPrevYear' => 'Tahun lalu',
'FilterOperatorPrevYearShort' => 'Tahun lalu',

'NullAsString' => 'KOSONG',
'ManageDetail' => 'Kelola rincian untuk "%s"',

'AdministrationPanel' => 'Panel Admin',
'CreateUser' => 'Buat Pengguna',
'Name' => 'Nama',
'AllFormFieldsAreRequired' => 'Semua kolom harus diisi.',
'Close' => 'Tutup',
'ChangePasswordForUser' => 'Ubah kata sandi untuk pengguna',
'ChangeYourPassword' => 'Ubah kata sandi anda',
'CurrentPassword' => 'Kata sandi saat ini',
'NewPassword' => 'Kata sandi baru',
'ChangePassword' => 'Ubah kata sandi',
'RenameUser' => 'Ganti nama pengguna',
'AddUser' => 'Tambah pengguna...',
'Permissions' => 'Hak akses',
'Rename' => 'Ubah nama',
'LoadingDots' => 'Memuat...',
'PageName' => 'Nama halaman',
'Admin' => 'Admin',
'Select' => 'Pilih',
'Update' => 'Perbaharui',
'Insert' => 'Tambahkan',
'Delete' => 'Hapus',
'AdminPage' => 'Panel admin',
'Application' => 'Aplikasi',
'Download' => 'unduh',
'PasswordChanged' => 'Kata sandi diubah',

'Select2MatchesOne' => 'Satu hasil tersedia, tekan enter untuk menapilkanya.',
'Select2MatchesMoreOne' => '%d hasil tersedia, gunakan tombol panah atas dan bawah untuk menavigasi.',
'Select2NoMatches' => 'Tidak ditemukan kecocokan',
'Select2AjaxError' => 'Gagal memuat data',
'Select2InputTooShort' => 'Silahkan masukan data minimal %d karakter',
'Select2InputTooLong' => 'Silahkan hapus data sebanyak %d karakter',
'Select2SelectionTooBig' => 'Anda hanya bisa menampilkan sebanyak %d item',
'Select2LoadMore' => 'Memuat lebih banyak hasil...',
'Select2Searching' => 'Mencari...',

'MultipleColumnSorting' => 'Sortir Banyak',
'Column' => 'Kolom',
'Order' => 'Urutan',
'Sort' => 'Urutkan',
'AddLevel' => 'Tambah tingkat',
'DeleteLevel' => 'Hapus tingkat',
'Ascending' => 'Ascending',
'Descending' => 'Descending',
'SortBy' => 'Urutkan berdasarkan',
'ThenBy' => 'Kemudian berdasarkan',

'And' => 'dan',

'CalendarMonths' => 'Januari_Februari_Maret_April_Mei_Juni_Juli_Agustus_September_Oktober_November_Desember',
'CalendarMonthsShort' => 'Jan_Feb_Mar_Apr_Mei_Jun_Jul_Agu_Sep_Okt_Nov_Des',
'CalendarWeekdays' => 'Minggu_Senin_Selasa_Rabu_Kamis_Jumat_Sabtu',
'CalendarWeekdaysShort' => 'Min_Sen_Sel_Rab_Kam_Jum_Sab',
'CalendarWeekdaysMin' => 'Mg_Sn_Sl_Rb_Km_Jm_St',

'DeleteUserConfirmation' => 'Pengguna "%s" akan dihapus, apakah anda yakin?',

'ToggleDetails' => 'Tampilkan/sembunyikan rincian',
'ToggleAllDetails' => 'Tampilkan/sembunyikan semua rincian',
'GoToMasterDetailPage' => 'Pergi ke halaman master/detail',

'FormAdd' => 'tambahkan data lainya',
'PageDescription' => 'Deskripsi halaman',
'SidebarToggle' => 'Alihkan bilah sisi',

'Month' => 'Bulan',
'Year' => 'Tahun',
'Day' => 'Hari',
'Hour' => 'Jam',
'Minute' => 'Menit',
'Second' => 'Detik',
'Dayofweek' => 'Hari dalam seminggu',

'True' => 'Benar',
'False' => 'Salah',

'Search' => 'Cari',
'SearchEmptyResult' => 'Tidak ditemukan kecocokan',
'ReloadPageWithDefaults' => 'Jika kamu melihat pesan ini, silahkan <a class="alert-link" href="%s">ulangi halaman ini dengan konfigurasi awal</a>.',
'HomePage' => 'Halaman Beranda',
'AddMultipleRecords' => 'Tambah data sebanyak %s',

'ScreenSizeLg' => 'Desktop Besar',
'ScreenSizeMd' => 'Desktop',
'ScreenSizeSm' => 'Tablet',
'ScreenSizeXs' => 'Telepon Selular',

'ItemsSelected' => '%s data terpilih',
'ClearSelection' => 'Bersihkan pilihan',
'DeleteSelected' => 'Hapus',
'ViewSelected' => 'Lihat',
'EditSelected' => 'Ubah',
'PrintSelected' => 'Cetak',
'Compare'      => 'Bandingkan',
'CompareSelected' => 'Bandingkan',
'CompareRemove' => 'Hapus dari perbandingan',
'CompareShowDiff' => 'Tampilkan perbedaan',
'CompareShowAll' => 'Tampilkan semua',

'FileTooLarge' => '%s: Ukuran berkas terlalu besar (kode galat %s)',
'UploadError' => '%s: Berkas gagal diunggah (kode galat %s)',
'ServerError' => '%s: Kesalahan dalam server (kode galat %s)',

'NoFile' => 'Tidak ada berkas',

'Columns' => 'Kolom',
'SearchCondition' => 'Kondisi pencarian',
'SelectAll' => 'Pilih semua',
'InactivityTimeoutExpired' => 'Anda keluar dari aplikasi karena terlalu lama tidak aktif.',
'DataLoading' => 'Memuat data...',

'Register' => 'Daftar',
'RegistrationPageTitle' => 'Pendaftaran',
'Registration form' => 'Form Pendaftaran',
'AccountRegistered' => 'Anda berhasil terdaftar.<br>Sebuah link untuk mengaktifkan akun sudah dikirimkan ke %s.<br>Silahkan cek pesan tersebut di email anda.',
'AccountVerified' => 'Anda telah berhasil memverifikasi akun Anda. Anda sekarang dapat masuk.',
'AccountHasNotBeenVerified' => 'Akun Anda belum diverifikasi. Harap ikuti petunjuk di email Anda untuk menyelesaikan verifikasi.',
'AccountVerificationFailed' => 'Verifikasi akun gagal.',
'SignInHere' => 'Sudah memiliki akun? <a href="login.php">Masuk di sini</a>',
'RegisterHere' => 'Tidak punya akun? <a href="register.php">Daftar disini</a>',
'RequestPasswordReset' => 'Minta penyetelan ulang kata sandi',
'SendPasswordResetLink' => 'Kirim tautan setel ulang sandi',
'ForgotPassword' => 'Lupa kata sandi Anda? <a href="recover_password.php">Pulihkan di sini</a>',
'UsernameOrEmail' => 'Username atau email',
'PasswordRecovery' => 'Pemulihan kata sandi',
'RecoveringPasswordInfo' => 'Silakan masukkan nama pengguna Anda yang Anda gunakan untuk mendaftar atau alamat email Anda.',
'AccountNotFound' => 'Tidak dapat menemukan akun Anda. Coba lagi.',
'RecoveringPasswordLinkSent' => 'Tautan untuk mereset kata sandi Anda telah dikirim ke email Anda.',
'Reset' => 'Setel ulang',
'ResetPassword' => 'Mereset password Anda',
'PasswordResetSuccessfully' => 'Kata sandi Anda telah berhasil direset!',
'PasswordResetFailed' => 'Reset kata sandi gagal',
'UserExists' => 'User ID %s telah digunakan.',
'EmailExists' => 'Email %s telah digunakan.',
'EditUser' => 'Ubah pengguna',
'ResendVerificationEmailHere' => 'Tidak menerima email verifikasi? <a href="resend_verification.php">Kirim ulang here</a>',
'ResendVerificationEmail' => 'Mengirim ulang email verifikasi',
'Resend' => 'Resend',
'ResendVerificationEmailPageInfoMessage' => 'Silakan masukkan alamat email yang Anda gunakan untuk mendaftar.',
'ResendVerificationAccountVerified' => 'akun sudah di verifikasi. kamu sekarang ke <a href="login.php">login</a>.',
'VerificationLinkResent' => 'Tautan untuk memverifikasi akun Anda telah dikirim ke email Anda.',
'Status' => 'Status',
'AccountVerificationRequired' => 'Dibutuhkan verifikasi akun.',
'PasswordResetRequested' => 'Permintaan reset Katasandi berhasil.',
'Deleting' => 'Menghapus...',
'MultiEdit' => 'Perubahan Banyak',
'Apply' => 'Terapkan',
'FieldsToBeUpdated' => 'Kolom yang akan diperbarui',
'UploadFiles' => 'Unggah berkas',
'MultiUpload' => 'Unggah banyak',
'Upload' => 'Unggah',
'Clear' => 'Bersihkan',
'ClearFieldsToBeUpdated' => 'Bersihkan bidang untuk diperbarui',
'RemoveAll' => 'Menghapus semua',
'ShowSelectedOnly' => 'lihat yang dipilih',
'ShowUnselectedOnly' => 'lihat yang tidak terpilih',
'OnlySelectedRecordsAreShown' => 'perlihatkan yang terpilih',
'OnlyUnselectedRecordsAreShown' => 'perlihatkan yang tidak terpilih',
'SelectionFilter' => 'Seleksi filter',
'ShowAll' => 'perlihatkan semua',
'PasswordAndConfirmationPasswordMustMatch' => 'password dan konfirmasi harus sama',
'RecaptchaMissingInputSecret' => 'reCAPTCHA: parameter secret hilang',
'RecaptchaInvalidInputSecret' => 'reCAPTCHA: parameter secret salah',
'RecaptchaMissingInputResponse' => 'selesaikan reCAPTCHA',
'RecaptchaInvalidInputResponse' => 'reCAPTCHA: parameter respon salah',
'RecaptchaBadRequest' => 'reCAPTCHA: request salah',
'RecaptchaTimeout' => 'reCAPTCHA: respon tidak valid atau habis waktu',
);
