<?php

return array(
'AccessDenied' => 'Akses ditolak',
'EditOperationNotPermitted' => 'Tidak diizinkan mengedit data',
'ViewOperationNotPermitted' => 'Tidak diizinkan melihat data',
'DeleteOperationNotPermitted' => 'Tidak diizinkan menghapus data',
'InsertOperationNotPermitted' => 'Tidak diizinkan menambahkan data',
'OperationNotPermitted' => 'Operasi tidak diizinkan',
'AccessDeniedErrorSuggestions' => '<p>Anda tidak memiliki izin untuk mengakses halaman ini. Bisa disebabkan oleh salah satu dari beberapa alasan:</p><ol> <li>Anda belum masuk. Silahkan masuk ke <a class="alert-link" href="%s">Halaman login</a> dan coba kembali.</li> <li>atau anda mungkin tidak memiliki hak akses untuk menjalankan operasi ini.</li> </ol>',
'ClientValidationsErrors' => 'Kesalahan:',
'SaveNewRecord' => 'Simpan',
'BackToList' => 'Kembali ke daftar',
'InsertRecord' => 'Tambah data',
'RequiredField' => 'Kolom harus diisi',
'Save' => 'Simpan',
'SetNull' => 'Atur kosong (NULL)',
'SetDefault' => 'Atur sebagai standar',
'AdvancedSearch' => 'Pencarian lanjutan',
'SearchFor' => 'Mencari data untuk',
'AllConditions' => 'Semua kondisi',
'AnyCondition' => 'Kondisi apapun',
'ApplyAdvancedFilter' => 'Terapkan',
'ResetAdvancedFilter' => 'Atur ulang',
'PageList' => 'Daftar halaman',
'ApplySimpleFilter' => 'Terapkan',
'ResetSimpleFilter' => 'Atur ulang',
'MasterRecord' => 'Data utama',
'ReturnFromDetailToMaster' => 'kembali ke daftar',
'AddNewRecord' => 'Tambah baru',
'PageNumbetOfCount' => 'Halaman {$current_page} dari {$page_count}',
'Delete' => 'Hapus',
'ExportToExcel' => 'Ekspor ke Excel',
'ExportToWord' => 'Ekspor ke Word',
'ExportToXml' => 'Ekspor ke Xml',
'ExportToCsv' => 'Ekspor ke Csv',
'ExportToPdf' => 'Ekspor ke Pdf',
'PrintCurrentPage' => 'Cetak halaman ini',
'PrintAllPages' => 'Cetak semua halaman',
'CurrentPage' => 'Halaman ini',
'PrinterFriendly' => 'Halaman untuk dicetak',
'PageSettings' => 'Pengaturan halaman',
'Appearance' => 'Tampilan',
'ViewMode' => 'Mode lihat',
'CardViewMode' => 'Kartu',
'TableViewMode' => 'Grid',
'CardRowCount' => 'Jumlah kartu dalam satu baris',
'CardRowCountDescription' => 'Di sini Anda dapat memilih jumlah kartu yang akan ditempatkan berturut-turut untuk setiap resolusi layar yang didukung. Resolusi Anda saat ini disorot <strong class="text-success">dalam tanda ini</strong>.',
'View' => 'Lihat',
'Edit' => 'Ubah',
'Copy' => 'Duplikasi',
'KeepImage' => 'Simpan',
'RemoveImage' => 'Hapus',
'ReplaceImage' => 'Ganti',
'FieldValueRequiredErrorMsg' => '%s harus diisi',
'LoggedInAs' => 'Masuk sebagai',
'YouAreNotLoggedIn' => 'Anda belum masuk',
'NoDataToDisplay' => 'Tidak ada data untuk ditampilkan',
'Refresh' => 'Segarkan',
'BinaryDataCanNotBeExportedToXls' => 'Data biner tidak dapat diekspor',
'DetailPreview' => 'Pratinjau detail',
'ShownFirstMofNRecords' => 'Menampilakan %s pertama dari %s data', /* masih rancu */
'FullView' => 'Tampilan penuh',
'RecordsMtoKFromN' => 'Dara %s ke %s dari %s',
'Login' => 'Masuk',
'Guest' => 'Tamu',
'LoginAsGuest' => 'Masuk sebagai tamu',
'Username' => 'User ID',
'Password' => 'Katasandi',
'ConfirmPassword' => 'Konfirmasi katasandi',
'ConfirmedPasswordError' => 'Katasandi tidak sama, silahkan ulangi kembali',
'RememberMe' => 'Ingat saya',
'LoginTitle' => 'Masuk',
'Print' => 'Cetak',
'Export' => 'Ekspor',
'more' => 'lainya',
'CloseWindow' => 'Tutup jendela',
'Back' => 'Kembali',
'Error' => 'Eror',
'ShowErrorDetails' => 'Tampilkan detail',
'CriticalErrorSuggestions' => 'Terjadi kesalahan yang tidak diharapkan. Mungkin karena salah satu dari beberapa alasan:<ul>
<li>Anda mencoba memasukkan data yang salah atau melakukan operasi ilegal;</li>
<li>koneksi ke server telah hilang.</li>
</ul>',
'Not' => 'Tidak',
'ShowHideNavbar' => 'Tampilkan/Sembunyikan Navbar',
'First' => 'Pertama',
'Last' => 'Terakhir',

'equals' => 'sama dengan',
'doesNotEquals' => 'tidak sama dengan',
'isLessThan' => 'kurang dari',
'isLessThanOrEqualsTo' => 'kurang dari atau sama dengan',
'isGreaterThan' => 'lebih besar dari',
'isGreaterThanOrEqualsTo' => 'lebih besar atau sama dengan',
'Like' => 'seperti',
'AnyField' => 'Kolom apapun',
'between' => 'diantara',
'isBlank' => 'datanya kosong',
'isNotBlank' => 'datanya tidak kosong',
'All' => 'Semua',

'Logout' => 'Keluar aplikasi',
'StartsWith' => 'dimulai dengan',
'EndsWith' => 'diakhiri dengan',
'Contains' => 'mengandung',
'SearchCondtitions' => 'kondisi pencarian',
'GuestAccessDenied' => 'Akses untuk tamu tidak diizinkan',
'UsernamePasswordWasInvalid' => 'Kombinasi User ID dan Katasandi yang dimasukan tidak sesuai.',

'ErrorsDuringUpdateProcess' => 'Terjadi kesalahan saat memperbaharui data:',
'ErrorsDuringInsertProcess' => 'Terjadi kesalahan dalam menambahkan data:',
'ErrorsDuringDeleteProcess' => 'Terjadi kesalahan dalam menghapus data:',
'ErrorsDuringDataRetrieving' => 'Gagal menerima data:',

'FileSizeExceedMaxSizeForField' => 'Maksimal ukuran file adalah %s (ukuran Data: %s, maksimal ukuran data: %s) ',
'ImageSizeExceedMaxSizeForField' => 'Maksimal ukuran gambar adalah %s (ukuran gambar: %dx%d, maksimal ukuran gambar: %dx%d) ',

'Actions' => 'Aksi',
'PleaseSelect' => 'Silahkan Pilih...',
'PrintOneRecord' => 'Cetak',

'ChangePageSizeText' => 'Total data: {$row_count}.',
'ChangePageSizeTitle' => 'Ukuran Halaman',
'CustomizePageSize' => '{$rec_count_per_page} data perhalaman',
'RecordsPerPage' => 'Data perhalaman',
'CurrentPageCount' => '{$current_page_count} halaman.',
'CustomRecordsPerPage' => 'Kustom',
'CountRowsWithCountPages' => '{$record_count} ({$page_count} halaman)',
'TotalPages' => 'Total halaman',
'UseCustomPageSize' => 'Gunakan data kustom',
'ViewMode' => 'Mode tampilan',

'EmptyFilter_MessageTitle' => 'Filter kosong',
'EmptyFilter_Message' => 'Harap mengisi setidaknya satu bidang pencarian.',
'Cancel' => 'Batal',
'Ok' => 'Oke',
'Commit' => 'Proses',

'RequiredValidationMessage' => '%s harus diisi.',
'EmailValidationMessage' => 'Silahkan masukan email yang valid.',
'UrlValidationMessage' => 'Silahkan masukan URL yang valid.',
'NumberValidationMessage' => 'Silahkan masukan angka yang valid.',
'DigitsValidationMessage' => 'Masukan hanya digit angka saja.',
'CreditcardValidationMessage' => 'Silahkann masukan kartu kredit yang valid.',
'MaxlengthValidationMessage' => 'Maksimal karakter yang bisa diinput adalah {0} karakter.',
'MinlengthValidationMessage' => 'Silahkan Masukan data minimal {0} karakter.',
'RangelengthValidationMessage' => 'Silahkan masukan data antara {0} sampai {1} karakter.',
'RangeValidationMessage' => 'Silahkan masukan data antara {0} sampai {1}.',
'MaxValidationMessage' => 'Harap masukkan nilai kurang dari atau sama dengan {0}.',
'MinValidationMessage' => 'Masukkan nilai yang lebih besar atau sama dengan {0}.',
'RegExpValidationMessage' => 'Nilai tidak sesuai dengan ekspresi reguler.',

'SaveAndBackToList' => 'Simpan dan kembalikan ke daftar',
'SaveAndInsert' => 'Simpan dan tambahkan data lain',
'SaveAndEdit' => 'Simpan dan lanjutkan pengeditan',

'NotLike' => 'Tidak Seperti',
'NotContains' => 'Tidak mengandung',
'isNotBlank' => 'Tidak Kosong',
'None' => 'Tidak ada',
'CreateFilterConditionFirst' => 'Untuk menampilkan data, <a href="#" class="js-filter-builder-open">buka Filter Builder</a> dan tentukan satu atau beberapa ketentuan. Anda juga dapat menggunakan alat Pencarian Cepat atau Filter Kolom.',
'CreateFilter' => 'Buat filter',
'EditFilter' => 'Ubah filter',
'ResetFilter' => 'Ulangi filter',

'Equals' => 'Sama dengan',
'DoesNotEquals' => 'Tidak sama dengan',
'IsLessThan' => 'Kurang dari',
'IsLessThanOrEqualsTo' => 'Kurang dari atau sama dengan',
'IsGreaterThan' => 'Lebih besar dari',
'IsGreaterThanOrEqualsTo' => 'Lebih besar atau sama dengan',
'Like' => 'Seperti',
'IsBlank' => 'Kosong',
'IsNotBlank' => 'Tidak boleh kosong',
'IsLike' => 'Seperti',
'IsNotLike' => 'Tidak seperti',
'Contains' => 'Mengandung',
'DoesNotContain' => 'Tidak mengandung',
'BeginsWith' => 'Dimulai dengan',
'EndsWith' => 'Diakhir oleh',

'OperatorAnd' => 'Semua',
'OperatorOr' => 'Apapun',
'OperatorNone' => 'Tidak ada',
'OperatorStringAnd' => 'Dan',
'OperatorStringOr' => 'Atau',
'OperatorStringNone' => 'Tidak',

'Loading' => 'Memuat',
'FilterBuilder' => 'Pembuat filter',
'FilterBuilderGroupConditionBeforeRules' => 'Pilih data dimana',
'FilterBuilderGroupConditionAfterRules' => 'dari yang berikut ini',
'DeleteSelectedRecordsQuestion' => 'Hapus data yang dipilih?',

'AddGroup' => 'Tambahkan grup',
'AddCondition' => 'Tambahkan kondisi',
'RemoveGroup' => 'Hapus grup',
'RemoveCondition' => 'Hapus kondisi',
'EnableFilter' => 'Enable filter',
'DisableFilter' => 'Disable filter',
'DefaultPageSize' => 'Define page size',
'SaveChanges' => 'Save changes',
'SaveAndOpenDetail' => 'Save and open "%s" details',
'QuickSearch' => 'Quick search',
'QuickSearchApply' => 'Search',
'QuickSearchClear' => 'Clear',
'DeleteRecordQuestion' => 'Delete record?',

'ResetFilterRow' => 'Reset filter row',
'ManageDetails' => 'Manage details',
'ErrorDetails' => 'Error details',
'SetToNull' => 'set to null',
'SetToDefault' => 'set to default',

'FilterOperatorEquals' => 'Equals',
'FilterOperatorEqualsShort' => '=',
'FilterOperatorDoesNotEqual' => 'Does not equal',
'FilterOperatorDoesNotEqualShort' => '<>',
'FilterOperatorIsGreaterThan' => 'Is greater than',
'FilterOperatorIsGreaterThanShort' => '>',
'FilterOperatorIsGreaterThanOrEqualTo' => 'Is greater than or equal to',
'FilterOperatorIsGreaterThanOrEqualToShort' => '>=',
'FilterOperatorIsLessThan' => 'Is less than',
'FilterOperatorIsLessThanShort' => '<',
'FilterOperatorIsLessThanOrEqualTo' => 'Is less than or equal to',
'FilterOperatorIsLessThanOrEqualToShort' => '<=',
'FilterOperatorIsBetween' => 'Is between',
'FilterOperatorIsBetweenShort' => 'Is between',
'FilterOperatorIsNotBetween' => 'Is not between',
'FilterOperatorIsNotBetweenShort' => 'Is not between',
'FilterOperatorContains' => 'Contains',
'FilterOperatorContainsShort' => 'Contains',
'FilterOperatorDoesNotContain' => 'Does not contain',
'FilterOperatorDoesNotContainShort' => 'Does not contain',
'FilterOperatorBeginsWith' => 'Begins with',
'FilterOperatorBeginsWithShort' => 'Begins with',
'FilterOperatorEndsWith' => 'Ends with',
'FilterOperatorEndsWithShort' => 'Ends with',
'FilterOperatorIsLike' => 'Is like',
'FilterOperatorIsLikeShort' => 'Is like',
'FilterOperatorIsNotLike' => 'Is not like',
'FilterOperatorIsNotLikeShort' => 'Is not like',
'FilterOperatorIsBlank' => 'Is blank',
'FilterOperatorIsBlankShort' => 'is blank',
'FilterOperatorIsNotBlank' => 'Is not blank',
'FilterOperatorIsNotBlankShort' => 'is not blank',
'FilterOperatorDateEquals' => 'Date equals',
'FilterOperatorDateEqualsShort' => 'Date =',
'FilterOperatorDateDoesNotEqual' => 'Date does not equal',
'FilterOperatorDateDoesNotEqualShort' => 'Date <>',
'FilterOperatorYearEquals' => 'Year equals',
'FilterOperatorYearEqualsShort' => 'Year =',
'FilterOperatorYearDoesNotEqual' => 'Year does not equal',
'FilterOperatorYearDoesNotEqualShort' => 'Year <>',
'FilterOperatorMonthEquals' => 'Month equals',
'FilterOperatorMonthEqualsShort' => 'Month =',
'FilterOperatorMonthDoesNotEqual' => 'Month does not equal',
'FilterOperatorMonthDoesNotEqualShort' => 'Month <>',
'FilterOperatorIn' => 'In',
'FilterOperatorInShort' => 'In',
'FilterOperatorNotIn' => 'Not In',
'FilterOperatorNotInShort' => 'Not In',
'FilterOperatorToday' => 'Today',
'FilterOperatorTodayShort' => 'Today',
'FilterOperatorThisMonth' => 'This month',
'FilterOperatorThisMonthShort' => 'This month',
'FilterOperatorPrevMonth' => 'Previous month',
'FilterOperatorPrevMonthShort' => 'Previous month',
'FilterOperatorThisYear' => 'This year',
'FilterOperatorThisYearShort' => 'This year',
'FilterOperatorPrevYear' => 'Previous year',
'FilterOperatorPrevYearShort' => 'Previous year',

'NullAsString' => 'NULL',
'ManageDetail' => 'Manage "%s" details',

'AdministrationPanel' => 'Administration panel',
'CreateUser' => 'Create user',
'Name' => 'Name',
'AllFormFieldsAreRequired' => 'All form fields are required.',
'Close' => 'Close',
'ChangePasswordForUser' => 'Change password for user',
'ChangeYourPassword' => 'Change your password',
'CurrentPassword' => 'Current password',
'NewPassword' => 'New password',
'ChangePassword' => 'Change password',
'RenameUser' => 'Rename user',
'AddUser' => 'Add user...',
'Permissions' => 'Permissions',
'Rename' => 'Rename',
'LoadingDots' => 'Loading...',
'PageName' => 'Page name',
'Admin' => 'Admin',
'Select' => 'Select',
'Update' => 'Update',
'Insert' => 'Insert',
'Delete' => 'Delete',
'AdminPage' => 'Admin panel',
'Application' => 'Application',
'Download' => 'download',
'PasswordChanged' => 'Password changed',

'Select2MatchesOne' => 'One result is available, press enter to select it.',
'Select2MatchesMoreOne' => '%d results are available, use up and down arrow keys to navigate.',
'Select2NoMatches' => 'No matches found',
'Select2AjaxError' => 'Loading failed',
'Select2InputTooShort' => 'Please enter %d or more characters',
'Select2InputTooLong' => 'Please delete %d characters',
'Select2SelectionTooBig' => 'You can only select %d items',
'Select2LoadMore' => 'Loading more results...',
'Select2Searching' => 'Searching...',

'MultipleColumnSorting' => 'Multiple Sort',
'Column' => 'Column',
'Order' => 'Order',
'Sort' => 'Sort',
'AddLevel' => 'Add level',
'DeleteLevel' => 'Delete level',
'Ascending' => 'Ascending',
'Descending' => 'Descending',
'SortBy' => 'Sort by',
'ThenBy' => 'Then by',

'And' => 'and',

'CalendarMonths' => 'January_February_March_April_May_June_July_August_September_October_November_December',
'CalendarMonthsShort' => 'Jan_Feb_Mar_Apr_May_Jun_Jul_Aug_Sep_Oct_Nov_Dec',
'CalendarWeekdays' => 'Sunday_Monday_Tuesday_Wednesday_Thursday_Friday_Saturday',
'CalendarWeekdaysShort' => 'Sun_Mon_Tue_Wed_Thu_Fri_Sat',
'CalendarWeekdaysMin' => 'Su_Mo_Tu_We_Th_Fr_Sa',

'DeleteUserConfirmation' => 'User "%s" will be deleted. Are you sure?',

'ToggleDetails' => 'Show/hide details',
'ToggleAllDetails' => 'Show/hide all details',
'GoToMasterDetailPage' => 'Go to master/detail page',

'FormAdd' => 'add another record',
'PageDescription' => 'Page description',
'SidebarToggle' => 'Toggle side bar',

'Month' => 'Month',
'Year' => 'Year',
'Day' => 'Day',
'Hour' => 'Hour',
'Minute' => 'Minute',
'Second' => 'Second',
'Dayofweek' => 'Day of week',

'True' => 'True',
'False' => 'False',

'Search' => 'Search',
'SearchEmptyResult' => 'No matches',
'ReloadPageWithDefaults' => 'If you see this message for the first time, try to <a class="alert-link" href="%s">reload the page with the default settings</a>.',
'HomePage' => 'Home page',
'AddMultipleRecords' => 'Add %s records',

'ScreenSizeLg' => 'Large desktop',
'ScreenSizeMd' => 'Desktop',
'ScreenSizeSm' => 'Tablet',
'ScreenSizeXs' => 'Phone',

'ItemsSelected' => '%s item(s) selected',
'ClearSelection' => 'Clear selection',
'DeleteSelected' => 'Delete',
'ViewSelected' => 'View',
'EditSelected' => 'Edit',
'PrintSelected' => 'Print',
'Compare'      => 'Compare',
'CompareSelected' => 'Compare',
'CompareRemove' => 'Remove from comparison',
'CompareShowDiff' => 'Show differences',
'CompareShowAll' => 'Show all',

'FileTooLarge' => '%s: File is too large (error code %s)',
'UploadError' => '%s: File uploading failed (error code %s)',
'ServerError' => '%s: Server error occurred (error code %s)',

'NoFile' => 'No file',

'Columns' => 'Columns',
'SearchCondition' => 'Search condition',
'SelectAll' => 'Select all',
'InactivityTimeoutExpired' => 'You have been logged out due to inactivity.',
'DataLoading' => 'Data loading...',

'Register' => 'Register',
'RegistrationPageTitle' => 'Registration',
'Registration form' => 'Registration form',
'AccountRegistered' => 'You have successfully registered.<br>A link to activate your account has been sent to %s.<br>Please check your inbox and spam folders.',
'AccountVerified' => 'You have successfully verified your account. You can now login.',
'AccountHasNotBeenVerified' => 'Your account has not yet been verified. Please follow the instructions in your email to complete verification.',
'AccountVerificationFailed' => 'Account verification failed.',
'SignInHere' => 'Already have an account? <a href="login.php">Sign in here</a>',
'RegisterHere' => 'Don\'t have an account? <a href="register.php">Register here</a>',
'RequestPasswordReset' => 'Request a password reset',
'SendPasswordResetLink' => 'Send password reset link',
'ForgotPassword' => 'Forgot your password? <a href="recover_password.php">Recover it here</a>',
'UsernameOrEmail' => 'Username or email',
'PasswordRecovery' => 'Password recovery',
'RecoveringPasswordInfo' => 'Please enter your username you use to sign up or your email address.',
'AccountNotFound' => 'Couldn\'t find your account. Try again.',
'RecoveringPasswordLinkSent' => 'A link to reset your password has been sent to your email.',
'Reset' => 'Reset',
'ResetPassword' => 'Reset your password',
'PasswordResetSuccessfully' => 'Your password has been reset successfully!',
'PasswordResetFailed' => 'Password reset failed',
'UserExists' => 'Username %s is already in use.',
'EmailExists' => 'Email %s is already in use.',
'EditUser' => 'Edit user',
'ResendVerificationEmailHere' => 'Didn\'t receive a verification email? <a href="resend_verification.php">Resend it here</a>',
'ResendVerificationEmail' => 'Resend verification email',
'Resend' => 'Resend',
'ResendVerificationEmailPageInfoMessage' => 'Please enter the email address you used to register.',
'ResendVerificationAccountVerified' => 'Your account is already verified. You can now <a href="login.php">login</a>.',
'VerificationLinkResent' => 'A link to verify your account has been sent to your email.',
'Status' => 'Status',
'AccountVerificationRequired' => 'Account verification required',
'PasswordResetRequested' => 'Password reset requested',
'Deleting' => 'Deleting...',
'MultiEdit' => 'Multiple Edit',
'Apply' => 'Apply',
'FieldsToBeUpdated' => 'Fields to be updated',
'UploadFiles' => 'Upload files',
'MultiUpload' => 'Multi Upload',
'Upload' => 'Upload',
'Clear' => 'Clear',
'ClearFieldsToBeUpdated' => 'Clear fields to be updated',
'RemoveAll' => 'Remove all',
);